% title: Response to eLife Reviewers
% author: twab

% USAGE: 
% to compile this document:
%    R  >>> knitr::knit("response.Rnw")
%    sh >>> pdflatex response.tex


<<renv, echo=FALSE, cache=FALSE, results='hide'>>=

# prepare the R environment
root <- "~/projects/SwipProteomics"
renv::load(root,quiet=TRUE)
devtools::load_all(quiet=TRUE)

# global knitr options
library(knitr)
opts <- list(tidy=FALSE,message=FALSE,warning=FALSE,fig.width=4,fig.height=4.5)
do.call(opts_chunk$set,opts)

@


\documentclass[12pt]{article}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{amsthm}
\usepackage{caption}
\usepackage{fancyhdr}
\usepackage{graphicx}
\usepackage{tikz}
\usepackage{titlesec}
\usepackage{blkarray}
\usepackage[position=top]{subfig}
\usepackage[margin=1.0in]{geometry}
\usepackage{inconsolata} % for mono font \texttt
\usepackage{csquotes}

\pagestyle{fancy}
\pagenumbering{gobble} 
\setlength\parindent{0pt}
\graphicspath{ {./figs/} }
\captionsetup[figure]{font=small}

\title{eLife Response}
\author{Tyler W. A. Bradshaw\\
  \small{Duke University, Department of Neurobiology}\\
  \small{Durham, NC USA}}

\lhead{Tyler W. A. Bradshaw}
\rhead{Response to eLife Reviewers} 


\begin{document}

\setlength{\abovedisplayskip}{3pt}
\setlength{\belowdisplayskip}{3pt}

\maketitle

\section{Reanalysis of Proteomics Data}

In our submitted manuscript, 
\textit{"Genetic Disruption of WASHC4 Drives Endo-lysosomal Dysfunction 
and Cognitive-Movement Impairments in Mice and Humans"}, we described the 
analysis of two protein mass spectrometry experiments:

\begin{enumerate}
	\item \textbf{WASH1 iBioID}
	\item \textbf{WASHC4 spatial TMT-Proteomics} 
\end{enumerate}

At the center of the cogent critique of our manuscript 
was the questioned statistical validity of our previously described approach.   
Succinctly, the issue at question is whether or not the R package \texttt{edgeR}
is an appropriate tool for analysis of protein mass spectrometry data.\\

Statistical inference in edgeR is built on a 
negative binomial (NB), generalized linear model (GLM) framework. 
Therefore, the data are assumed to be adequately described by a NB distribution 
parameterized by a dispersion parameter, $\phi$. \footnotemark{} \\

\footnotetext{ The dispersion parameter can take several forms. 
\texttt{edgeR} supports three dispersion models: 'common', 'trended', and 
'tagwise'. However, when using \texttt{edgeR's} 
robust quasi-likelihood test methods, only global (i.e. 'common' or 'trended') 
dispersion metrics are appropriate 
(see \texttt{edgeR::glmQLFit's} documentation).}

Previously we used a customized workflow \footnotemark{} to preprocess
and normalize the data prior to performing statistical testing using
\texttt{edgeR's} flexible GLM framework. However, we failed to thoughougly
consider the overall adequacy of the NB framework for mass spectrometry data. 
Here we reconsider its appropriatness for our TMT proteomics dataset.  \\

\footnotetext{ The most important step in our normalization approach is 
IRS normalization. MS2 random sampling results in identification and
quantification of proteins by different peptides in each MS experiment.
To account for this source of variability, protein measurements are adjusted by
a scaling factor such that the geometric mean of all internal reference
standards are equal (Plubell et al., 2017).
This is essential to account for the stochasticisity of peptide
quantification in MS experiments. Phillip Wilmarth's GitHub offers an 
excellent exploration of IRS normalization.
}

\begin{figure}[ht]
	\begin{center}
		\includegraphics[width=\textwidth]{gof}
		\caption{\textbf{Goodness-of-fit of \texttt{edgeR} (A), and 
		\texttt{MSstats} (B) statistical approaches.} The overall
		adequacy of the linear models fit to the data were assessed 
		by plotting the residual deviance for all proteins as a 
		quantile-quantile plot (McCarthy \textit{et al.}, (2012)). 
		\textbf{(A)} The normalized
		protein data were fit with a NB GLM of the form: 
		\texttt{Abundance} $\sim$ \texttt{Mixture + Condition}.
		Where \texttt{Mixure} is a blocking factor that accounts for
		sources of variablity between experiments. Protein-wise deviance
		statistics were transformed to normality and plotted aganis
		theoretical normal quantiles using \texttt{edgeR::gof}.
		\textbf{(B)}
		The normalized protein data were fit with a linear mixed-effects 
		model (LMM) of the form: 
		\texttt{Abundance} $\sim$ \texttt{0 + Condition + (1|Mixture)}. 
		Where \texttt{Mixture} indicates the random effect
		of \texttt{Mixture}. The residual deviance and degrees of 
		freedom were extracted from the fitted models, z-score
		normalized, and plotted as in (A). Proteins with a significantly 
		poor fit are indicated as outliers in blue 
		(Holm-adjusted P-value $<$ 0.05).}
		\label{fig:gof}
	\end{center}
\end{figure}

We evaluated the overall adequacy of the \texttt{edgeR} model by plotting the 
residual deviance of all proteins against their theoretical, 
normal quantiles in a quantile-quantile plot. \textbf{Figure \ref{fig:gof}} 
illustrates the overall lack of fit for the three disperion models fit by 
\texttt{edgeR}.  As an alternative to \texttt{edgeR} we considered 
\texttt{MSstatsTMT}, an extension of MSstats for analysis of TMT proteomics
experiments. \\

\texttt{MSstatsTMT} utilizes a linear mixed-model framework. The strength of 
linear mixed models (LMMs) is in their ability to account for complex sources of 
variation in an experimental design. 

\begin{displayquote}
	In a mixed model one or more covariates 
	are a categorical variable  representing experimental or 
	observational "units" in the data set. 
	[...]
	If the set of possible levels of the covariate is fixed and reproducible 
	we model the covariate using fixed-effects parameters. 
	If the levels that we observed represent a random sample from
	the set of all possible levels we incorporate random effects in the
	model.
\end{displayquote}

A TMT proteomics experiment consists of \texttt{m = 1...M} concatensions of 
isobaric-TMT labeled samples or \texttt{Mixtures}. 
Each TMT channel is dedicated to the analysis of \texttt{c = 1...C}
individual biological or treatment \texttt{Conditions} prepared from one
\texttt{b = 1...B} biological replicates or \texttt{Subjects}. 
A single mixture may be profiled in \texttt{t = 1...T} technical replicate 
mass spectrometry runs. 

We prepared 7 subcellular fractions (BioFraction) from 2 Conditions: 
Control and SWIP\textsuperscript{P1019R} Mutant mice. 
There were 6 Subjects, three bioreplicate Control and 
SWIP\textsuperscript{P1019R} Mutant mice.

\begin{figure}[h]
	\begin{center}
		\includegraphics[width=\textwidth]{design}
		\caption{\textbf{Experimental Design.} We utilized 16-plex 
		TMT tags to label samples prepared from 6 mice.}
		\label{fig:design}
	\end{center}
\end{figure}

In an experiment such as ours with multiple mixtures and biological replicates, 
but no technical replication of mixture (T = 1) \texttt{MSstatsTMT} fits a
linear mixed model of the following form to each protein:

Where Mixture is a mixed-effect and quantifies variation between TMT mixtures.
Condition is a fixed effect (mean = 0) and in our experiment represents the
interaction of terms \texttt{Genotype} and \texttt{BioFraction}. $\epsilon$ 
is a random effect representing both biological and technical variation, 
quantifying any remaining error. \\

\begin{equation} \label{eq1}
	Y_{mcbt} = \mu + Mixture_m + Condition_c + \epsilon_{mcbt}
\end{equation}

Where Mixture represents the random-effect of mixture and 
Condition is a fixed-effect and in our experiment is interaction of 
Genotype and BioFraction--the 14 combinations of 7 BioFractions fractions from 
Control and Mutant mice. $\epsilon_{mcbt}$ is the residual error ($\sigma^2$).\\

In our experimental design, we made measurments from seven BioFractions 
from each subject. Thus, we should include the term 
Subject, representing the 6 individual mice or subjects analyzed in our 
experiment. \\

\begin{equation} \label{eq2}
	Y_{mcbt} = \mu + Mixture_m + Condition_c + Subject_b + \epsilon_{mcbt}
\end{equation}

However, in our design \texttt{Mixture} is confounded with the
term \texttt{Subject} -- in each mixture we analyzed all \texttt{BioFractions} 
from a single Control and Mutant mouse. Thus we can choose to account for the 
effect of \texttt{Mixture} or \texttt{Subject}, but not both. 
Assuming Mixture contributes greater to the variance, we drop the term Subject,
and the reduced model is equivalent  to \ref{eq1}. \\

Model based testing of differential abundance between pairs of conditions
is assessed through contrast of conditioned means estimated by fitting the
parameters of the model by REML to obtain $\hat{\beta}$, $\sigma^2$ and
$\hat{V}$.

The degrees of freedom are determined by the Satterthwaite approximation[REF],
and the T-statistic for the contrast is taken to be (lmerTest ref): \\

\begin{equation}
	t = \frac{l^T * \hat{\beta}}{sqrt(l * \sigma^2 * \hat{V} * l^T)}
\end{equation}

$\sigma^2$ is the error from \textbf{Equation} \ref{eq1}.
$l^T$ is a vector specifying a contrast between positive and 
negative coefficients in the model.

Together, the denominator $\sqrt(l * \sigma^2 * \hat{V} * l^T)$ is the 
standard error of the contrast.

<<fit0, eval=TRUE, echo=TRUE>>=

library(dplyr)
library(data.table)

## load SwipProteomics data
data(swip)
data(gene_map)
data(msstats_prot)
data(alt_contrast)
data(msstats_contrasts)

## formula to be fit:
fx0 <- formula("Abundance ~ 0 + Condition + (1|Mixture)")

# fit the model
idx <- msstats_prot$Protein == swip
fm <- lmerTest::lmer(fx0, msstats_prot[idx,])

# calculate model statistics
model_summary <- summary(fm,ddf="Satterthwaite")

df <- model_summary$coefficients
df %>% as.data.table(keep.rownames="Coefficient") %>% knitr::kable()

# evaluate goodness-of-fit
r2_nakagawa <- r.squaredGLMM.merMod(fm)
knitr::kable(rbind(c("marginal/fixef", "conditional/total"), r2_nakagawa))

contrast <- msstats_contrasts[1,]
lmerTestContrast(fm,contrast) %>% knitr::kable()

@


\end{document}
